### PR TITLE
UWPOCR.au3 - COM ErrorHandling + Au3Check compability

### PR DESCRIPTION
**Pull request by mlipok**
Also fixed Au3Check compability

### CODE REVIEW

**Comment by Danyfirex** [comment]
I do not agree with adding ErrorHandler  in each function. Adding once at the main will handle any all event in deep functions
````AutoIt
Local $oErrorHandler = ObjEvent("AutoIt.Error", "__UWPOCR_ErrorHandler")
#forceref $oErrorHandler
````

**Comment by mlipok** [comment]
> Adding once at the main will handle any all event in deep functions

do you mean this:
```
Func _UWPOCR_GetText($sImageFilePathOrhBitmap, $sLanguageTagToUse = Default, $bUseOcrLine = False)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", "__UWPOCR_ErrorHandler")
	_UWPOCR_Log("_UWPOCR_GetText")
	Return __UWPOCR_GetText($sImageFilePathOrhBitmap, $sLanguageTagToUse, $bUseOcrLine)
EndFunc   ;==>_UWPOCR_GetText
```

?

If so, my answer is no - you're wrong.

**Comment by mlipok** [comment]
When you leaving function then `Local $oErrorHandler` is destroyed/cleared.
Take a look here:
https://www.autoitscript.com/autoit3/docs/functions/ObjEvent.htm

```
Func Example()
    ; Error monitoring. This will trap all COM errors while alive.
    ; This particular object is declared as local, meaning after the function returns it will not exist.
    Local $oErrorHandler = ObjEvent("AutoIt.Error", "_ErrFunc")
```

**Comment by Danyfirex** [comment]
Yes I know It's released when function ends but remember it exists while all internal functions are called so we don't need register it in internal functions each time. Check this demonstration:

```AutoIt

Global $g_oObject = 0

_Example()
;error handler will not exist so F2 will arise an ERROR
_F2()

Func _Example()
	;this error handler will exist till all functions an internal functions are called (it's what I need handle all till exit _Example)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", "_ErrFunc")
	_F1() ;call object methods in internal functions
EndFunc   ;==>_Example


Func _InitializeObject()
	$g_oObject = ObjCreate("shell.application")
EndFunc   ;==>_InitializeObject

Func _F1()
	_InitializeObject()
	_F2() ;force Unknown name error
EndFunc   ;==>_F1

Func _F2()
	$g_oObject.F2()  ;error handled OK here
	_F3()
EndFunc   ;==>_F2

Func _F3()
	$g_oObject.F3() ;error handled OK here
EndFunc   ;==>_F3

; User's COM error function. Will be called if COM error occurs
Func _ErrFunc($oError)
	; Do anything here.
	ConsoleWrite(@ScriptName & " (" & $oError.scriptline & ") : ==> COM Error intercepted !" & @CRLF & _
			@TAB & "err.number is: " & @TAB & @TAB & "0x" & Hex($oError.number) & @CRLF & _
			@TAB & "err.windescription:" & @TAB & $oError.windescription & @CRLF & _
			@TAB & "err.description is: " & @TAB & $oError.description & @CRLF & _
			@TAB & "err.source is: " & @TAB & @TAB & $oError.source & @CRLF & _
			@TAB & "err.helpfile is: " & @TAB & $oError.helpfile & @CRLF & _
			@TAB & "err.helpcontext is: " & @TAB & $oError.helpcontext & @CRLF & _
			@TAB & "err.lastdllerror is: " & @TAB & $oError.lastdllerror & @CRLF & _
			@TAB & "err.scriptline is: " & @TAB & $oError.scriptline & @CRLF & _
			@TAB & "err.retcode is: " & @TAB & "0x" & Hex($oError.retcode) & @CRLF & @CRLF)
EndFunc   ;==>_ErrFunc
```

**Comment by mlipok** [comment]
ha interesting....
Must to check this type of scoping....

**Comment by mlipok** [comment]
I'm wondering COM error handler should be used for:

```AutoIt
Func _UWPOCR_GetSupportedLanguages()
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __UWPOCR_ErrorHandler)
	#forceref $oErrorHandler

	If Not __UWPOCR_Initialize() Then
		_UWPOCR_Log("FAIL __UWPOCR_Initialize")
		Return SetError(@error, @extended, 0)
	EndIf
	_UWPOCR_Log("OK __UWPOCR_Initialize")
	Return $__g_aLanguageInfo2D
EndFunc   ;==>_UWPOCR_GetSupportedLanguages
```

Due to the fact that this fucntion is used also in `_UWPOCR_GetSupportedLanguages()`

**Comment by Danyfirex** [comment]
Yes It should be used there.

**Comment by mlipok** [comment]
Done.
Check it, review .... merge... if you wish ;)

**Pull request merged**
